# Generated by Django 5.1.1 on 2024-09-27 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=10, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=10, verbose_name='Долгота')),
                ('height', models.CharField(max_length=10, verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('fam', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otc', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('other_titles', models.CharField(max_length=50, unique=True)),
                ('connect', models.CharField(max_length=50, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('pen', 'На рассмотрении'), ('acp', 'Принято'), ('rej', 'Отклонено')], default='new', max_length=3)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.URLField(verbose_name='Ссылка на изображение')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Описание изображения')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.pereval', verbose_name='Изображения')),
            ],
        ),
    ]
