# Generated by Django 5.1.1 on 2024-09-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.CharField(max_length=2000, verbose_name='Cсылка на изображение'),
        ),
    ]
