# Generated by Django 5.1.1 on 2024-09-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_images_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.CharField(max_length=10, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.CharField(max_length=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.CharField(max_length=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='beauty_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
